### ISSUE TITLE
Build.sh error (curl i386)

### ISSUE THREAD

**Issue by linusix** [jasonacox/Build-OpenSSL-cURL#38]
Error occurs in curl i386.

Xcode 11.2.1

git clone https://github.com/jasonacox/Build-OpenSSL-cURL.git

cd Build-OpenSSL-cURL.git

./build.sh

==> /tmp/curl-7.68.0-iOS-i386-bitcode.log <==
checking for sys/socket.h... (cached) yes
checking for recv... no
configure: error: Unable to link function recv

[curl-7.68.0-iOS-i386-bitcode.log](https://github.com/jasonacox/Build-OpenSSL-cURL/files/4496978/curl-7.68.0-iOS-i386-bitcode.log)

**Comment by jasonacox** [comment]
I'm not able to get the same failure.  This could occur if the nghttp2 library to build property but you would have seen that error as well.  I'm using Xcode Version 11.4.1.  Since the i386 architecture for iOS is only for the simulator and is likely not needed anymore, you can remove the `buildIOS "i386"` and related lines from the `./curl/libcurl-build.sh` script.
