### ISSUE TITLE
Preview not working: linker command failed

### ISSUE THREAD

**Issue by MatteCarra** [jasonacox/Build-OpenSSL-cURL#46]
Since I started developing with XCode 12 beta I have been unable to use the preview tool for my app.
When I try to render the preview the linking process fails with exit code 1:
```
ld: in /PATH_TO_FILE/libcrypto.a(bio_b64.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have built openssl without http2 support.
The project is building and running fine for the emulator and for iphones and ipads. The preview is the only thing that is not working.
Please let me know if you need any information.

Thanks a lot for your useful scripts!

**Comment by jasonacox** [comment]
Hi @MatteCarra thanks for the kind note!  

As to the error, are you using the Mac Catalyst libraries that are built by the script (use `./build.sh -m`) or are you using the standard iOS +Mac fat binaries?

The Catalyst binaries should be stored here:
   openssl/Catalyst/lib/libcrypto.a are: x86_64
   openssl/Catalyst/lib/libssl.a are: x86_64
   nghttp2/lib/libnghttp2_Catalyst.a are: x86_64
   curl/lib/libcurl_Catalyst.a are: x86_64

I haven't been using these so I'll need to try to replicate the error you are getting.

**Comment by jasonacox** [comment]
Ok @MatteCarra - I'm able to get a build without errors.

In addition to the existing FAT libraries you have for iOS and the iOS-simulator, you should build the Mac Catalyst libraries and copy the Catalyst libraries to your project (replace *~/project/libs* with your real project folder):

```bash
./build -m.   # This will build with Mac Catalyst libraries

# Copy the Catalyst libraries to your project
cp openssl/openssl-ios-x86_64-maccatalyst.a ~/project/libs
cp nghttp2/lib/libnghttp2_Catalyst.a ~/project/libs
cp curl/lib/libcurl_Catalyst.a ~/project/libs
```

Drag these `*.a` file into your project under the "Frameworks" folder.  In the project "General" tab, update the libraries to be the right "Platform" with *iOS* select for the FAT libraries and *macOS* for the Catalyst binaries:

<img width="514" alt="Screen Shot 2020-09-13 at 9 12 18 PM" src="https://user-images.githubusercontent.com/836718/93043151-d3fc0600-f605-11ea-8f71-9f7a3eb91c1c.png">

I've updated the iOS example so that it automatically builds for Mac Catalyst as well (I'll check it in tonight):

<img width="901" alt="Screen Shot 2020-09-13 at 9 17 18 PM" src="https://user-images.githubusercontent.com/836718/93043411-87fd9100-f606-11ea-93cb-6456d7942e0a.png">

**Comment by MatteCarra** [comment]
Thanks for your answer!
I'm currently using the standard iOS +Mac fat binaries, no Mac Catalyst.
I'm almost sure I have the *.a files in the section you are mentioning, but I will have a look as soon as possible.
I want to make it clear that the app builds and runs fine on the simulator or device, but only fails to build in the UI preview (in my case a simple SwiftUI project).

**Comment by MatteCarra** [comment]
I can confirm that the issue is present in your example project as well.
Steps to reproduce:
1) Change the iOS Development Target to >= iOS 13.0 ( I selected 14.0), in the Project settings
2) Right click -> Add file -> Add SwiftUI file
3) Resume the preview of the SwiftUI preview
The build process will fail with the said issue.

I wouldn't rule out the possibility that this is an xcode bug.

Thanks again!

**Comment by jasonacox** [comment]
Ah!  I see.  I can only set target to 13.7.  I'm still on Xcode 11.7.  I'll install a beta image and give it a try.  Thanks, Matteo.

**Comment by MatteCarra** [comment]
Thanks.
I just wanted to inform that x code 12 stable will most likely be released today

**Comment by MatteCarra** [comment]
Xcode 12 GM seed has fixed the issue.
It was an xcode issue all along.
Thanks for your help!

**Comment by jasonacox** [comment]
That's great news!  Thanks, Matteo.

I have a request - I would love to add a Swift openssl/libcurl example to this repo.  Would you be interested in helping?  If so, submit a pull request or send me a note!

Stay safe!
Jason

**Comment by MatteCarra** [comment]
I think I can do that!
I will update you as soon as I have something in my hands!
